# Pre-commit hooks for code formatting and linting
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check for merge conflict markers
      - id: check-merge-conflict

      # Check YAML syntax
      - id: check-yaml
        args: ["--unsafe"] # Allow custom YAML tags used in ROS

      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict

      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Ensure files end with a newline
      - id: end-of-file-fixer

      # Check for broken symlinks
      - id: check-symlinks

  # Python code formatting with black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix, --extend-select=I]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--quiet]
